language: go
go:
  - 1.1
  - tip

install:
  - gem install nats
  - go get -v ./...
  - go get -v github.com/onsi/ginkgo
  - go install -v github.com/onsi/ginkgo/ginkgo
  - pushd ../../coreos/etcd
  - ./build
  - mv ./etcd $HOME/gopath/bin
  - popd

script: PATH=$HOME/gopath/bin:$PATH ginkgo -r  -i -race --randomizeAllSpecs --failOnPending --skipMeasurements